### ISSUE TITLE
error on restarting docker run

### ISSUE THREAD

**Issue by cordoval** [remind101/conveyor#46]
This happens when i restart the docker run
```bash
ubuntu@ip-10-0-0-86:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND              CREATED             STATUS                      PORTS               NAMES
b17ce773be35        remind101/conveyor:master   "/go/bin/conveyor"   24 seconds ago      Exited (2) 22 seconds ago                       conveyor
ubuntu@ip-10-0-0-86:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ip-10-0-0-86:~$ docker logs b17ce773be35
Starting 4 workers
Starting server on 8080
2015/12/28 21:28:54 sqs error: %v InvalidParameter: 1 validation errors:
- missing required parameter: Entries
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x51767c]

goroutine 9 [running]:
github.com/remind101/conveyor.(*SQSBuildQueue).handleError(0xc20803b920, 0x7ff16ccb2030, 0xc20825df80)
	/go/src/github.com/remind101/conveyor/queue.go:186 +0x15c
github.com/remind101/conveyor.func·004()
	/go/src/github.com/remind101/conveyor/queue.go:119 +0x7f
created by github.com/remind101/conveyor.(*SQSBuildQueue).Subscribe
	/go/src/github.com/remind101/conveyor/queue.go:122 +0xe4

goroutine 1 [chan receive]:
main.mainAction(0xc2080b00b0)
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:66 +0x297
github.com/codegangsta/cli.(*App).Run(0xc20805c300, 0xc20800a000, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:130 +0xbb9
main.main()
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:47 +0x3d6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/honeybadger-io/honeybadger-go.func·003()
	/go/src/github.com/remind101/conveyor/Godeps/_workspace/src/github.com/honeybadger-io/honeybadger-go/buffered_worker.go:12 +0x86
created by github.com/honeybadger-io/honeybadger-go.newBufferedWorker
	/go/src/github.com/remind101/conveyor/Godeps/_workspace/src/github.com/honeybadger-io/honeybadger-go/buffered_worker.go:25 +0x13d

goroutine 7 [chan receive]:
main.runWorker(0x7ff16ccb2580, 0xc20803b920, 0xc2080b00b0, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/cmd/conveyor/worker.go:86 +0x40a
main.func·001()
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:59 +0x43
created by main.mainAction
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:60 +0x1cd

goroutine 8 [select]:
main.runServer(0x7ff16ccb2580, 0xc20803b920, 0xc2080b00b0, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/cmd/conveyor/server.go:60 +0x54d
main.func·002()
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:63 +0x43
created by main.mainAction
	/go/src/github.com/remind101/conveyor/cmd/conveyor/main.go:64 +0x26f

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc2080791e0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080791e0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208079180, 0x0, 0x7ff16ccb1c58, 0xc20800bd58)
	/usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038178, 0x475264, 0x0, 0x0)
	/usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208038178, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080428a0, 0x7ff16ccb3b30, 0xc208038178, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080428a0, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20800bd50, 0x5, 0x7ff16ccb2a68, 0xc208086420, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1808 +0xba
main.func·003()
	/go/src/github.com/remind101/conveyor/cmd/conveyor/server.go:57 +0xb4
created by main.runServer
	/go/src/github.com/remind101/conveyor/cmd/conveyor/server.go:58 +0x445

goroutine 16 [select]:
github.com/remind101/conveyor.(*Worker).Start(0xc2080351c0, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/worker.go:102 +0x4f3
created by github.com/remind101/conveyor.Workers.Start
	/go/src/github.com/remind101/conveyor/worker.go:18 +0x6c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc2080b0630)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

goroutine 18 [select]:
github.com/remind101/conveyor.(*Worker).Start(0xc208035200, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/worker.go:102 +0x4f3
created by github.com/remind101/conveyor.Workers.Start
	/go/src/github.com/remind101/conveyor/worker.go:18 +0x6c

goroutine 19 [select]:
github.com/remind101/conveyor.(*Worker).Start(0xc208035240, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/worker.go:102 +0x4f3
created by github.com/remind101/conveyor.Workers.Start
	/go/src/github.com/remind101/conveyor/worker.go:18 +0x6c

goroutine 20 [select]:
github.com/remind101/conveyor.(*Worker).Start(0xc208035280, 0x0, 0x0)
	/go/src/github.com/remind101/conveyor/worker.go:102 +0x4f3
created by github.com/remind101/conveyor.Workers.Start
	/go/src/github.com/remind101/conveyor/worker.go:18 +0x6c

goroutine 30 [runnable]:
net/http.(*persistConn).readLoop(0xc2080b0630)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f
```

**Comment by cordoval** [comment]
would be nice to have e.g. notes, like sqs://xyz where xyz is defined like this ...

**Comment by ejholmes** [comment]
Believe https://github.com/remind101/conveyor/pull/42 fixes this?
